site_name: FlyBrainLab Client Documentation
docs_dir: sources
site_description: 'Documentation for FlyBrainLab Client.'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'red'


nav:
    - Home: index.md
    - Core: client.md
    - Widgets: widgets.md